# Generated by Django 4.1 on 2022-08-12 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-updated_on', '-created_on']},
        ),
    ]
